##################################
#                                #
# Configuration for RHTintHealth #
#                                #
##################################

# Messages
messages:
  prefix: '&8[&9&lRHTintHealth&8]'
  reload: '%prefix% &7The configuration has been refreshed'
  no-permission: "%prefix% &cYou don't have the permission for that."
  tint:
    enabled: '%prefix% &7Damage tint is now &aenabled&7.'
    disabled: '%prefix% &7Damage tint is now &cdisabled&7.'

#Tint
tint:
  minimum-damage: 1
  intensity-modifier: 1
  fade:
    enabled: true
    time: 5

# Commands
commands:
  tinthealth:
    usage:
      - '/tinthealth'
      - '/tinthealth reload'
      - '/tinthealth toggle'